// Test for DecodeImage (stb_image-backed PNG/JPEG decode). Fixtured on two
// small synthetic PNGs generated for this test suite (not real artwork):
//
//   tests/fixtures/weather_icon.png (50x50 RGB): every pixel's color is a
//   known formula -- r=(x*5)%256, g=(y*5)%256, b=128 -- generated by the
//   same script that created the file, so exact values are ground truth,
//   not assumed.
//
//   tests/fixtures/transparency_test.png (2x2 RGBA), hand-verified via
//   `xxd` for its real dimensions:
//     $ xxd -l 24 tests/fixtures/transparency_test.png
//     00000000: 8950 4e47 0d0a 1a0a 0000 000d 4948 4452  .PNG........IHDR
//     00000010: 0000 0002 0000 0002                      ........
//   (width/height bytes both 00 00 00 02 -> 2x2). Its four pixels are
//   opaque red, fully-transparent green, opaque blue, and mostly-
//   transparent yellow (alpha=40) -- set explicitly when generating it.
//
// Run via: ctest --test-dir build

#include "watchpanel/image_decode.h"

#include <iostream>

namespace {

int failures = 0;

void Check(bool condition, const char *what) {
    if (!condition) {
        std::cerr << "FAILED: " << what << std::endl;
        ++failures;
    }
}

void CheckPixel(const watchpanel::DecodedImage &img, int x, int y,
                 int r, int g, int b, int a, const char *what) {
    const uint8_t *p = img.At(x, y);
    if (p[0] != r || p[1] != g || p[2] != b || p[3] != a) {
        std::cerr << "FAILED: " << what << " -- got (" << int(p[0]) << "," << int(p[1]) << ","
                   << int(p[2]) << "," << int(p[3]) << "), expected (" << r << "," << g << "," << b
                   << "," << a << ")" << std::endl;
        ++failures;
    }
}

}  // namespace

int main() {
    using namespace watchpanel;

    // --- Gradient fixture: verify real decode against a known formula ---
    DecodedImage gradient;
    Check(DecodeImage("tests/fixtures/weather_icon.png", &gradient), "gradient PNG decodes");
    Check(gradient.width == 50, "gradient width is 50");
    Check(gradient.height == 50, "gradient height is 50");

    // r=(x*5)%256, g=(y*5)%256, b=128, alpha=255 (no source alpha channel).
    CheckPixel(gradient, 0, 0, 0, 0, 128, 255, "gradient (0,0)");
    CheckPixel(gradient, 49, 0, (49 * 5) % 256, 0, 128, 255, "gradient (49,0)");
    CheckPixel(gradient, 0, 49, 0, (49 * 5) % 256, 128, 255, "gradient (0,49)");
    CheckPixel(gradient, 49, 49, (49 * 5) % 256, (49 * 5) % 256, 128, 255, "gradient (49,49)");
    CheckPixel(gradient, 25, 25, (25 * 5) % 256, (25 * 5) % 256, 128, 255, "gradient (25,25)");

    // --- Transparency fixture: verify the real alpha channel decodes ---
    DecodedImage rgba;
    Check(DecodeImage("tests/fixtures/transparency_test.png", &rgba), "transparency PNG decodes");
    Check(rgba.width == 2 && rgba.height == 2, "transparency fixture is 2x2");

    CheckPixel(rgba, 0, 0, 255, 0, 0, 255, "opaque red");
    CheckPixel(rgba, 1, 0, 0, 255, 0, 0, "fully transparent green");
    CheckPixel(rgba, 0, 1, 0, 0, 255, 255, "opaque blue");
    CheckPixel(rgba, 1, 1, 255, 255, 0, 40, "mostly-transparent yellow");

    // --- Negative cases ---
    DecodedImage notAnImage;
    Check(!DecodeImage("tests/fixtures/weather_data.json", &notAnImage), "non-image file is rejected");

    DecodedImage missing;
    Check(!DecodeImage("tests/fixtures/does_not_exist.png", &missing), "missing file is rejected");

    if (failures == 0) {
        std::cout << "OK (image_decode checks passed)" << std::endl;
        return 0;
    }
    std::cerr << failures << " check(s) failed" << std::endl;
    return 1;
}
